### ISSUE TITLE
Enable Server-to-Client Sync

### ISSUE THREAD

**Issue by martin2250** [socratesx/myrsync#1]
Hi,

this app is exactly what I need. I want to sync my music library from my PC to my phone. Right now I have to shut down my phone, take out the SD card and plug it into my computer to use regular rsync. This app would be so much more convenient. There is only the issue of SD card permissions on Android 6+, would this app work rightaway or is there any workaround for you to enable this?

Cheers
Martin

**Comment by socratesx** [comment]
Hi Martin,
Thanks for your comment. Right now the app uses the opposite direction. I could try to add support for your use case. I will let you know when this happen so to try it.

**Comment by socratesx** [comment]
Well after working a lot on this, I concluded that the function can be implemented but somewhat limited as newer versions of android set a lot of limits for file access on external sd. However, if the phone has root access then there is no limit to save anywhere in any folder. But if no root access is available then only a predefined folder can be used. 

So, I will implement it that way and leave the user to select one of the predefined folders to rsync with the server in pull mode. Actually, the current commit has already this feature working so you can test it out. If you have root then you can enable it from settings. Beware only that the module is not finished and you may hit some bugs. Please let me know if this works for you.

Regards

**Comment by martin2250** [comment]
Hi Socrates,

unfortunately I need to sync folders on my SD card, which I can't move to another location. I've since written [my own](https://github.com/martin2250/linux-common/blob/master/bin/adb-sync) (pretty limited) version of rsync, which runs over ADB and can sync directly to any folder. ~If~ When I root my phone, I'll give myrsync another shot.

Best
Martin

**Comment by socratesx** [comment]
Feature Implemented, so I am going to close this issue. 

Best Regards,
Socrates
