### ISSUE TITLE
Options keep getting unchecked

### ISSUE THREAD

**Issue by martin2250** [socratesx/myrsync#6]
Hi Socrates,

on my phone, the checkbox-options n, m and t keep getting unchecked when I save the configuration and open it again.

Martin

**Comment by socratesx** [comment]
Hi Martin,

I cannot replicate it in my phone. Did you update from an old version of myrsync? If yes can you please reinstall?

Best regards
Socrates

-------- Original Message --------

**Comment by martin2250** [comment]
Hi Socrates,

no, I'm using a fresh install of Android and this is the first time that myrsync was installed on this phone.
-t and -m was tested using the configuration shown in the screenshot attached to the other issue, m was only tested by checking every box and seeing which ones were not checked afterwards.

Best
Martin

**Comment by socratesx** [comment]
OK I found the problems and fixed them. Can you please try the new version and let me know if the app is working properly now?

Best Regards,
Socrates

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by martin2250** [comment]
Hi, sorry for the delay. Options are preserved now. Thanks!
